# Production Docker Compose configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  api:
    environment:
      - NODE_ENV=production
    command: npm start
    restart: unless-stopped
    # Remove development volumes
    volumes: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/external/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  hub:
    environment:
      - NODE_ENV=production
    command: npm start
    restart: unless-stopped
    # Remove development volumes
    volumes: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    restart: unless-stopped
    # In production, you might want to use an external database
    # and remove the port exposure for security
    ports: []
    environment:
      - DB_NAME=${DB_NAME:-alohawaii_prod}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD} # Must be set in production
