services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: alohawaii-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../api/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - alohawaii-network

  # API Service
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: alohawaii-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
      - ../api/.env.local
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      - NEXTAUTH_URL=http://localhost:4000
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../api:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - alohawaii-network

  # Staff Hub Dashboard
  hub:
    build:
      context: ../hub
      dockerfile: Dockerfile
    container_name: alohawaii-hub
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../hub/.env.local
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    volumes:
      - ../hub:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - alohawaii-network
    profiles:
      - hub # Only start with --profile hub

volumes:
  postgres_data:

networks:
  alohawaii-network:
    driver: bridge
